const BLista = [
      {
        id: '1',
        nazwa: 'Bukiet Róże różne',
        cena: 100,
        image: "https://i.ibb.co/6Rp28Nh/b1.jpg",
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Róże, Czerwony, Czerwone, Biały, Białe, Różne',
      },
      {
        id: '2',
        nazwa: 'Róże',
        cena: 150,
        image: 'https://i.ibb.co/s5jDQHT/b2.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Róże, Lilia, Różowe, Róż, Czerwony, Czerwone, Biały, Białe, Różne',
      },
      {
        id: '3',
        nazwa: 'Bukiet 3',
        cena: 200,
        image: 'https://i.ibb.co/qWD5PcB/b3.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Tulipan, Purpurowy, Róż, Różowy, żółty, Różne',
      },
      {
        id: '4',
        nazwa: 'Bukiet Różne',
        cena: 250,
        image: 'https://i.ibb.co/rkpzb97/bukiet4.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Róże, Różowy, Róż, Goździki, Goździk, Różne',
      },
      {
        id: '5',
        nazwa: 'Kolorowy wiosenny bukiet',
        cena: 250,
        image: 'https://i.ibb.co/p1f7Z4P/b5.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Różowy, Róż, Różowy, Fiolet, Stokrotka, żółty, Pomarańczowy, Biały, Białe, Różne',
      },
      {
        id: '6',
        nazwa: 'Bukiet 6',
        cena: 250,
        image: 'https://i.ibb.co/F7qpSmx/b6.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Różowy, Róż, Czerwony, Czerwone, Biały, Białe, Różne, Piwonia, Stokrotka',
      },
      {
        id: '7',
        nazwa: 'Bukiet 7',
        cena: 250,
        image: 'https://i.ibb.co/WPJXG1Y/b7.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Tulipan, Róż, Różowy, Biały, Białe, Różne',
      },
      {
        id: '8',
        nazwa: 'Bukiet 8',
        cena: 250,
        image: 'https://i.ibb.co/RjVBRC6/b8.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża,Nagietek, Zółty, Czerwony, Czerwone, Różne',
      },
      {
        id: '9',
        nazwa: 'Bukiet 9',
        cena: 250,
        image: 'https://i.ibb.co/569Gwdj/b9.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Niebieski, Żółty, Różne',
      },
      {
        id: '10',
        nazwa: 'Bukiet 10',
        cena: 250,
        image: 'https://i.ibb.co/0Mf666R/b10.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Lilia, Róż, Różowy, Różne',
      },
      {
        id: '11',
        nazwa: 'Bukiet 11',
        cena: 250,
        image: 'https://i.ibb.co/1dmBgLp/b11.jpg',
        opis: 'Bukiet składa się z...Kwiatów',
        tagi: 'Róża, Żółty, Mak, Różne',
      },
    ];
export {BLista};

const FBLista = [
  {
    id: '1',
    nazwa: 'Kwiaty',
    cena: 100,
    image: "https://i.ibb.co/hXv7hZn/bukiet1.jpg",
    opis: 'FlowerBox składa się z...Kwiatów w pudełku',
    tagi: 'Róża, Róż, Różowy, Biały, Białe, Różne',
  },
  {
    id: '2',
    nazwa: 'Róże',
    cena: 100,
    image: "https://i.ibb.co/7ywmS9L/fb2.jpg",
    opis: 'FlowerBox składa się z...Kwiatów w pudełku',
    tagi: 'Róża, Róż, Różowe, Różowy, Żółty, Żółte, Różne',
  },
  {
    id: '3',
    nazwa: 'Róże białe',
    cena: 100,
    image: "https://i.ibb.co/QDFD0Bd/fb3.jpg",
    opis: 'FlowerBox składa się z...Kwiatów w pudełku',
    tagi: 'Róża, Róże, Biały, Białe, Mono',
  },
];
export {FBLista};

const ZLista = [
  {
    id: '1',
    nazwa: 'Róże i Rafaello',
    cena: 100,
    image: "https://i.ibb.co/ZTZ5cfp/z1.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róże, Czerwony, Czerwone, Różne, Rafaello, Słodycze',
  },
  {
    id: '2',
    nazwa: 'Róże i Wino',
    cena: 100,
    image: "https://i.ibb.co/NxQQwLx/z2.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róże, Czerwony, Czerwone, Mono',
  },
  {
    id: '3',
    nazwa: 'Tulipany i merci',
    cena: 100,
    image: "https://i.ibb.co/q9s70vX/z3.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Tulipan, Tulipany, Róż, Różowy, Merci, Czekoladki, Słodycze, Mono',
  },
  {
    id: '4',
    nazwa: 'Róże i miś',
    cena: 100,
    image: "https://i.ibb.co/bJ929mw/z4.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róże, Róż, Różowy, Różowe, Mono, miś, pluszak',
  },
  {
    id: '5',
    nazwa: 'Róże i wino',
    cena: 100,
    image: "https://i.ibb.co/1mPTwtz/z5.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róże, Czerwony, Czerwone, Wino, Alkohol, Mono',
  },
  {
    id: '6',
    nazwa: 'Kwiaty i wino',
    cena: 100,
    image: "https://i.ibb.co/PQ6nRxL/z6.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Aster, Róża, Dzika, Róż, Różowe Biały, Białe, Wino, Alkohol, Różne',
  },
  {
    id: '7',
    nazwa: 'Kwiaty i baryłki',
    cena: 100,
    image: "https://i.ibb.co/wQ4ZNs0/z7.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róż, Różowy, Czerwony, Czerwone, Piwonia, Piwonie, Różne, Baryłki, Czekoladki, Wedel, Słodycze',
  },
  {
    id: '8',
    nazwa: 'Bukiet z misiem',
    cena: 100,
    image: "https://i.ibb.co/VSr4YqV/z8.jpg",
    opis: 'Zestaw składa się z...Kwiatów',
    tagi: 'Róża, Róże, Czerwony, Czerwone, Róż, Różowy, Biały, Białe, Różne, miś, pluszak',
  },
];
export {ZLista};